name: flutter_geofence
description: Plugin to interact with geofences, and get the user's current/latest location.
version: 0.4.4
homepage: https://github.com/DwayneCoussement/geofence

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.intivoto.flutter_geofence
        pluginClass: FlutterGeofencePlugin
      ios:
        pluginClass: FlutterGeofencePlugin